# Generated by Django 3.2.7 on 2023-08-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('keywords', models.TextField()),
                ('bid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('campaign_fund', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('status', models.CharField(choices=[('ON', 'On'), ('OFF', 'Off')], default='OFF', max_length=3)),
                ('town', models.CharField(max_length=255)),
                ('radius', models.PositiveIntegerField()),
            ],
        ),
    ]
