# Generated by Django 3.2.7 on 2023-08-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_rename_city_town'),
    ]

    operations = [
        migrations.AddField(
            model_name='town',
            name='key',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
