# Generated by Django 3.2.7 on 2023-08-04 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_alter_campaign_town'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='town',
            name='key',
        ),
    ]
